server:
  port: 8082

spring:
  ## The most important feature... ever
  banner:
    location=classpath:/banner.txt
  r2dbc:
    name: books-database
    username: book
    password: book
    url: r2dbc:postgres://localhost:5432/books_database
booknumbers:
  api:
    url: http://127.0.0.1:8081/api/numbers
    timeout_sec: 2
